migrate to uwsgi-tasks
There is a bug when using @task(priority=2) with:
ValueError: spooler callable dictionary must contains only bytes

The error happens because priority is an integer.